In [1]:
import pandas as pd
import numpy as np

# Title and Abstract Screening Portion

In [17]:
all_searches = pd.read_csv('2025-panczyk-slr-initial.csv')
print(len(all_searches))

630

In [21]:
title_subset = all_searches.sample(60)
title_subset.columns

Index(['Key', 'Item Type', 'Publication Year', 'Author', 'Title',
       'Publication Title', 'ISBN', 'ISSN', 'DOI', 'Url', 'Abstract Note',
       'Date', 'Date Added', 'Date Modified', 'Access Date', 'Pages',
       'Num Pages', 'Issue', 'Volume', 'Number Of Volumes',
       'Journal Abbreviation', 'Short Title', 'Series', 'Series Number',
       'Series Text', 'Series Title', 'Publisher', 'Place', 'Language',
       'Rights', 'Type', 'Archive', 'Archive Location', 'Library Catalog',
       'Call Number', 'Extra', 'Notes', 'File Attachments', 'Link Attachments',
       'Manual Tags', 'Automatic Tags', 'Editor', 'Series Editor',
       'Translator', 'Contributor', 'Attorney Agent', 'Book Author',
       'Cast Member', 'Commenter', 'Composer', 'Cosponsor', 'Counsel',
       'Interviewer', 'Producer', 'Recipient', 'Reviewed Author',
       'Scriptwriter', 'Words By', 'Guest', 'Number', 'Edition',
       'Running Time', 'Scale', 'Medium', 'Artwork Size', 'Filing Date',
       'Application Number', 'Assignee', 'Issuing Authority', 'Country',
       'Meeting Name', 'Conference Name', 'Court', 'References', 'Reporter',
       'Legal Status', 'Priority Numbers', 'Programming Language', 'Version',
       'System', 'Code', 'Code Number', 'Section', 'Session', 'Committee',
       'History', 'Legislative Body'],
      dtype='object')

In [37]:
title_subset = title_subset[["Author", "Publication Year", "Title", "DOI"]]
title_subset

,Author,Publication Year,Title,DOI
84,"Huegli, David; Chavaillaz, Alain; Sauer, Juerg...",2025,Effects of false alarms and miscues of decisio...,10.1080/00140139.2025.2453546
413,"Fleury, Emmanuelle; Pignol, Jean Philippe; Kil...",2025,Stereotactic radiation therapy or protons for ...,10.1016/j.ijrobp.2025.06.3867
341,"Khan, Ehsan; Lambrakis, Kristina; Briffa, Tom;...",2025,Re-engineering the clinical approach to suspec...,10.1016/j.ahj.2025.02.016
53,"Gutierrez-Zaballa, Jon; Basterretxea, Koldo; E...",2024,Evaluating single event upsets in deep neural ...,10.1016/j.sysarc.2024.103242
544,"Silvey, Scott; Patel, Nilang; Liu, Jinze; Tafa...",2024,A machine learning algorithm avoids unnecessar...,10.1016/j.cgh.2024.06.015
347,"Moosavi, Amirhossein; Huang, Steven; Vahabi, M...",2024,Prospective human validation of artificial int...,10.1016/j.jacadv.2024.101202
63,"Cankaya, Burak; Topuz, Kazim; Delen, Dursun; G...",2023,Evidence-based managerial decision-making with...,10.1016/j.omega.2023.102906
553,"Bellelli, Valeria; Siccardi, Guido; Conte, Liv...",2020,Preliminary attempt to predict risk of invasiv...,10.3390/antibiotics9100644
628,"Jeong, Ji Yun; Jeon, Jae Han; Bae, Kwi Hyun; C...",2018,Smart care based on telemonitoring and telemed...,10.1089/tmj.2017.0203
562,"Acheampong, Emmanuel; Adua, Eric; Obirikorang,...",2024,Predictive modelling of metabolic syndrome in ...,10.1007/s40200-024-01491-7
466,"Herke, Habil Csongor; Szabó, Barbara",2024,Self-driving vehicles and their impact on the ...,10.53955/jhcls.v4i3.376
505,"Renard, Jade; Faucher, Mathieu R.; Combes, Ana...",2021,Machine-learning algorithm as a prognostic too...,10.1177/1098612X211001273
145,"Kim, Woojin; Kim, Junghwa; Jang, Jeong Ah; Kim...",2023,Do perceptions of hydrogen energy effect on ve...,10.1007/s12205-022-0227-x
455,"Abu, N. S.; Bukhari, W. M.; Adli, M. H.; Maghf...",2024,"Advancements, challenges and safety implicatio...",10.18196/jrc.v5i3.21114
232,"Nam, Su Han; Kwon, Jae Hyun; Kim, Young Do",2023,Comparison of optimal machine learning algorit...,10.3390/toxics11040314
132,"Loken, Erik Andreas; Lokkevik, Jens; Sui, Dan",2020,Data-driven approaches tests on a laboratory d...,10.1007/s13202-020-00870-z
509,"Javaid, Sabah; Gorji, Hamed Taheri; Soulami, K...",2023,Identification and ranking biomaterials for bo...,10.1007/s42600-022-00257-5
133,"Suryana, Lucas Elbert; Nordhoff, Sina; Calvert...",2025,Meaningful human control of partially automate...,10.1016/j.trf.2025.04.026
108,"Mehta, Aryan Alpesh; Padaria, Ali Asgar; Bavis...",2024,Securing the future: a comprehensive review of...,10.1109/ACCESS.2023.3347200
165,"Ahmad, Usman",2022,A node pairing approach to secure the Internet...,10.1016/j.jocs.2022.101718
167,"Yalcin, Mustafa; Sari, Fatih; Yildiz, Ahmet",2023,Exploration of potential geothermal fields usi...,10.1016/j.geothermics.2023.102792
77,"de Silva, Brian M.; Callaham, Jared; Jonker, J...",2021,Hybrid learning approach to sensor fault detec...,10.2514/1.J059943
106,"Ji, Yuxiong; Xu, Zhongke; Zhao, Cong; Chen, Ku...",2025,Accelerated testing and evaluation for black-b...,10.1109/TITS.2024.3525059
391,"Gui, Chengzhi; Cao, Chen; Zhang, Xin; Zhang, J...",2023,Radiomics and artificial neural networks model...,10.3389/fcvm.2023.1173769
382,"Chen, Ai; Zhong, Hua; Peng, Jie; Luo, Tao; Jun...",2025,Machine learning-based modeling for predicting...,10.1016/j.wneu.2025.124018
423,"Najla, Mehyar; Mach, Pavel; Becvar, Zdenek",2020,Deep learning for selection between RF and VLC...,10.1109/LWC.2020.3003786
228,"Letkovsky, Stanislav; Jencova, Sylvia; Vasanic...",2024,Is artificial intelligence really more accurat...,10.3390/ijfs12010008
608,"Nedadur, Rashmi; Bhatt, Nitish; Chung, Jennife...",2025,Machine learning and decision making in aortic...,10.1016/j.jtcvs.2023.11.032
568,"Kherabi, Yousra; Messika, Jonathan; Peiffer-Sm...",2022,"Machine learning, antimicrobial stewardship, a...",10.1111/tid.13957
500,"Guo, Zhenya; Liu, Jiaping; Liang, Guozhi; Lian...",2024,Identification and validation of cuproptosis-r...,10.3389/fimmu.2024.1371446
216,"Nagappan, G.; Maheswari, K. G.; Siva, C.",2024,Enhancing intelligent transport systems: A cut...,10.1016/j.simpat.2024.102979
379,"Leidinger, Andreas; Zuckerman, Scott L.; Feng,...",2023,Predictors of spinal trauma care and outcomes ...,10.3171/2022.11.SPINE22763
151,"Minagawa, Hideaki; Tezuka, Tomoya; Tsuchida, H...",2024,Effective combinations of features in predicti...,10.1016/j.nimb.2024.165383
46,"Chinchilla, Monica; Santos-Martin, David; Carp...",2021,Worldwide annual optimum tilt angle model for ...,10.1016/j.apenergy.2020.116056
479,"Manonmani, Gangadharan; Ponmozhi, Krishnasamy;...",2025,The A3C-CCTSO-R2N2 algorithmic framework for p...,10.11591/eei.v14i5.8982
325,"Woo, Myung; Alhanti, Brooke; Lusk, Sam; Dunsto...",2020,Evaluation of ML-based clinical decision suppo...,10.3390/jpm10030104
324,"Hegde, Shwetha; Nanayakkara, Shanika; Cox, Ste...",2024,Australian dentists' knowledge of the conseque...,10.1002/cre2.70027
624,"Rodríguez, Andrés; Mendoza, Deibie; Ascuntar, ...",2021,Supervised classification techniques for predi...,10.1016/j.ajem.2020.09.013
359,"Cappelli, M.; Ambi, F.; Botta, E.; Cruz, J.; D...",2025,Advancements in central control for IFMIF-DONE...,10.1016/j.fusengdes.2025.115345
516,"Tariq, Zeeshan; Abu-Al-Saud, Moataz O.; Mahmou...",2025,Fast tracking of safe CO2 trapping indices usi...,10.1016/j.petlm.2025.01.002
142,"Mulero-Palencia, Sofia; Alvarez-Diaz, Sonia; A...",2021,Machine learning for the improvement of deep r...,10.3390/su13126576
169,"Han, Hua; Gao, Jiaqing; Gu, Bo; Ren, Zhengxiong",2025,Comprehensive study on building chiller fault ...,10.1080/23744731.2024.2402200
25,"Nasir, K. M. Zaheen; Chakma, Tanaya",2025,Constitutive modeling of anisotropic plasticit...,10.1080/00295450.2024.2410620
4,"Qi, Ben; Xiao, Xingyu; Liang, Jingang; Po, Li-...",2022,An open time-series simulated dataset covering...,10.1038/s41597-022-01879-1
327,"McCradden, Melissa D.; Joshi, Shalmali; Anders...",2020,Patient safety and quality improvement: Ethica...,10.1093/jamia/ocaa085
445,"Ding, Shukai; Qu, Jian",2022,A study on safety driving of intelligent vehic...,10.37936/ecti-cit.2022164.248674
524,"Bücker, Michael; Hoti, Kreshnik; Rose, Olaf",2024,Artificial intelligence to assist decision-mak...,10.1016/j.rcsop.2024.100491
221,"Rahbari, Dadmehr; Ahmed, Foisal; Jenihhin, Mak...",2024,Reliability-critical computation offloading in...,10.1109/JSYST.2024.3432449
537,"Komorowski, Matthieu; Celi, Leo A.; Badawi, Om...",2018,The Artificial Intelligence Clinician learns o...,10.1038/s41591-018-0213-5
598,"Park, Jeong Ho; Kim, Yushin; Lee, Kwang Jae; Y...",2019,Artificial neural network learns clinical asse...,10.1016/j.apmr.2019.03.016
518,"Pasta, Gilda; Frassanito, Luciano; Calabria, M...",2025,Personalized predictive hemodynamic management...,10.23736/S0375-9393.25.18937-2
307,"Wilson, F. Perry; Yamamoto, Yu; Martin, Meliss...",2023,A randomized clinical trial assessing the effe...,10.1038/s41467-023-38532-3
233,"Lalithadevi, B.; Krishnaveni, S.",2025,ExAIRFC-GSDC: An advanced machine learning-bas...,10.1007/s44196-025-00742-6
227,"Ananias, Estevao; Gaspar, Pedro D.; Soares, Va...",2021,Artificial intelligence decision support syste...,10.3390/electronics10192394
487,"Baruah, Arindam; Borkar, Hemant",2023,Optimised machine learning classification mode...,10.1016/j.matpr.2023.03.386
561,"Tran, Zachary; Zhang, Wenhao; Verma, Arjun; Co...",2022,The derivation of an International Classificat...,10.1097/TA.0000000000003416
392,"Bulstra, Anne Eva J.; Buijze, Geert A.; Cohen,...",2022,A machine learning algorithm to estimate the p...,10.1016/j.jhsa.2022.02.023
437,"Liu, Qinming; Chen, Huan; Chen, Jianing; Wang,...",2025,Cross model fusion-based fault diagnosis for e...,10.1016/j.measurement.2025.118203
23,"Li, Xinpeng; Song, Jiayue; Yang, Li; Li, Huant...",2024,Source term inversion coupling kernel principa...,10.1016/j.pnucene.2024.105171
582,"Iivanainen, Sanna; Ravichandra, Ravi; Jekunen,...",2023,ePRO symptom follow-up of colorectal cancer pa...,10.1007/s00432-023-04622-4

In [38]:
title_subset.to_csv('title_subset.csv')

# Full Text Screening Portion

In [71]:
full_text_excluded = pd.read_csv('excluded.csv')
print(len(full_text_excluded))
full_text_ex_subset = full_text_excluded.sample(n=8)
full_text_ex_subset = full_text_ex_subset[["Authors", "Published Year", "Title", "DOI"]]
col_map = {
    "Authors": "Author",
    "Published Year": "Publication Year",
    "Title": "Title",
    "DOI": "DOI"
}
full_text_ex_subset.rename(columns=col_map, inplace=True)
full_text_ex_subset.head()

79

,Author,Publication Year,Title,DOI
69,"Barbieri, Carlo; Molina, Manuel; Ponce, Pedro;...",2016,An international observational study suggests ...,10.1016/j.kint.2016.03.036
11,"de Silva, Brian M.; Callaham, Jared; Jonker, J...",2021,Hybrid learning approach to sensor fault detec...,10.2514/1.J059943
65,"Qiao, Wei; Cheng, Xianggang; Dou, Linming; He,...",2024,"Sedimentary environments, mechanical propertie...",10.12363/issn.1001-1986.24.04.0279
12,"Chiu, Tzu-Yi; Le Ny, Jerome; David, Jean-Pierre",2023,Temporal logic explanations for dynamic decisi...,10.1016/j.artint.2023.103897
29,"Alhaddad, Ulaa; Basuhail, Abdullah; Khemakhem,...",2023,Towards sustainable energy grids: a machine le...,10.3390/su151612622

# QA Screening Portion

In [64]:
final_included = pd.read_csv('2025-panczyk-slr-final.csv')
print(len(final_included))

78

In [66]:
qa_subset = final_included.sample(n=7)
qa_subset = qa_subset[["Author", "Publication Year", "Title", "DOI"]]
qa_subset.to_csv('qa_subset.csv')

# Merging QA Included with Full Text Excluded

In [72]:
full_text = pd.concat([qa_subset, full_text_ex_subset], ignore_index=True)
full_text_shuffled = full_text.sample(frac=1)
full_text_shuffled.to_csv('full_text_2.csv')